src/GprTool/GprTool.csproj, src/GprTool/Program.cs
Use Octokit.GraphQL.NET instead of RestSharp and hand crafted GraphQL / Json parsing!
- Use `Octokit.GraphQL.NET 0.1.4-packages-preview`
- Convert `list` command to use this
=> Refactor to use Octokit.GraphQL.NET

README.md, src/GprTool/Program.cs
List packages for a specific user or org (if specified).
- If an owner is specified, attempt to find org or user with that name
- Show warning when SAML enforced
- Show packages for current viewer when unspecified
Fixes #13
=> List packages for a specific user/org

src/GprTool/GprTool.csproj, src/GprTool/Program.cs
- Include the package type
- Update the GraphQL schema
E.g.
```
https://github.com/jcansdale/GitHubPackagesExample
OctocatApp (Nuget) [] (0 downloads)
https://github.com/jcansdale/gpr
gpr (Docker) [0.1.95-g5167f5fe04, 0.1.94-ge867c8eeab, 0.1.97-g0a1e4284e1, latest, 0.1.96-gf99a0903fc, 0.1.95-ged4d8a9f99, 0.1.94, 0.1.93, 0.1.92-g2f1a52d7e4, alpha, docker-base-layer] (4 downloads)
gpr (Nuget) [0.1.96-g2655089c02, 0.1.95-g5167f5fe04, 0.1.94-ge867c8eeab, 0.1.97-g0a1e4284e1, 0.1.96-gf99a0903fc, 0.1.95-ged4d8a9f99, 0.1.94, 0.1.93, 0.1.92-g2f1a52d7e4, 0.1.91-g4712918564, 0.1.90-g9b8168c586, 0.1.89-g78f280cb9c, 0.1.81, 0.1.80, 0.1.79, 0.1.78, 0.1.77, 0.1.82, 0.1.88-g6e4562a1a2, 0.1.81-gddcdb4b240, 0.1.80-gf082a28261, 0.1.78-g3a852e0245, 0.1.76, 0.1.74, 0.1.73-gf14999c3fc, 0.1.72-g823f26c261, …
```
=> Show the package type

.github/workflows/docker.yml, Dockerfile, src/GprTool/Program.cs
Still needs refinement, but it's already useful like this.
=> Allow docker image to use default read:packages token

src/GprTool/Program.cs
This PR adds package versions delete functionality. `PATH` can be a user, organization or repository.
The following command will list all package versions targeted for deletion:
```
gpr delete PATH -k TOKEN
```
The following command can be used to delete all package versions:
```
gpr delete PATH --force -k TOKEN
```
The following command can be used to clean-up orphaned `docker-base-layer` tags:
```
gpr delete PATH --docker-clean-up -k TOKEN
```
=> Add support for cleaning up orphaned docker layers

README.md, src/GprTool/Program.cs
The command will output something like this:
```
> gpr xmlencode TOKEN
This XML encoded token can be included in a public repository without being
automatically deleted by GitHub:
&#102;&#111;&#111;&#98;&#97;&#114;&#98;&#97;&#122;
For example, the following might be included in `nuget.config`:
<packageSourceCredentials>
<github>
<add key="Username" value="PublicToken" />
<add key="ClearTextPassword" value="&#102;&#111;&#111;&#98;&#97;&#114;&#98;&#97;&#122;" />
</github>
</packageSourceCredentials>
Or in a Maven `settings.xml` file:
<servers>
<server>
<id>github</id>
<username>PublicToken</username>
<password>&#102;&#111;&#111;&#98;&#97;&#114;&#98;&#97;&#122;</password>
</server>
</servers>
```
=> Add xmlEncode command for XML encodding tokens

src/GprTool/Program.cs
For example:
```
> gpr files jcansdale -k TOKEN
Octokit.GraphQL (242 downloads)
Octokit.GraphQL.0.1.4-packages-preview2.nupkg (16/02/2020, 79 downloads, 358889 bytes)
Octokit.GraphQL.0.1.4-packages-preview.nupkg (04/02/2020, 160 downloads, 358409 bytes)
Octokit.GraphQL.0.1.4-preview-package-deletes.nupkg (04/02/2020, 3 downloads, 353334 bytes)
Octokit.GraphQL.Core (242 downloads)
Octokit.GraphQL.Core.0.1.4-packages-preview2.nupkg (16/02/2020, 79 downloads, 46235 bytes)
Octokit.GraphQL.Core.0.1.4-packages-preview.nupkg (04/02/2020, 160 downloads, 46228 bytes)
Octokit.GraphQL.Core.0.1.4-preview-package-deletes.nupkg (04/02/2020, 3 downloads, 46227 bytes)
Octokit.GraphQL.Core.Generation (0 downloads)
Octokit.GraphQL.Core.Generation.0.1.4-preview-package-deletes.nupkg (04/02/2020, 0 …
```
=> Show storage used when listing files

src/GprTool/Program.cs
When using an `int`, total storage could overflow! 😊 
```
Storage used -1765 MB
```
Using a `long` fixes this.
=> Use long to count storage used (in bytes)

.github/workflows/dotnetcore.yml
- Build and test on Windows, Ubuntu and MacOS
- Only publish packages when building `jcansdale/gpr` (not forks)
- Publish to GitHub Packages for all branches
- Publish to `nuget.org` for `master` branch
=> Lots of improvements to workflow!

.github/workflows/docker.yml, src/GprTool/NuGetUtilities.cs, test/GprTool.Tests/NuGetUtilitiesTests.cs
`Metadata.Repository.Url` appears to return null if `<repository type=... />` hasn't been set. This happens when a project is built with `dotnet pack` and the `RepositoryUrl` property. We need to use `Metadata.ProjectUrl` instead!
=> Workaround for Metadata.Repository.Url being null

.github/workflows/dotnetcore.yml, GprTool.sln, src/GprTool/GprTool.csproj, src/GprTool/NuGetUtilities.cs, test/GprTool.Tests/NuGetUtilitiesTests.cs
_Note, I wanted to get this working again with minimal changes. I'm concerned it will be breaking people's builds. 😨_ 
`dotnet pack` will happily create a `<repository url="..." />` element that `Manifest.ReadFrom` isn't able to read. This is a fix for that.
- Remove the `PackageProjectUrl` and `RepositoryType` properties
- Publish `gpr` too using itself
- Implement `ReadNupkgManifest` using `NuspecReader.Xml`
- Reverted previous misadventure 😉 
I wasn't able to create a test .nupkg like this:
```
manifest.Metadata.Repository = new RepositoryMetadata
{
Url = repositoryUrl,
Type = null
};
```
...because without a `Type` no `<repository url="..."` element gets written.
The self-publish _does_ work, so I believe this is woking!
Fixes #60
=> Find the repository url attribute when the type attribute is missing

.github/workflows/dotnetcore.yml
- Simplify envvars
- Use `PackageOutputPath`
- Use `bash` as x-plat shell
=> Cleanup workflow

src/GprTool/Program.cs
- Don't keep trying or stop when a NuGet warning is returned
- Don't keep trying or stop when HTTP status 404 / NotFound is returned
- Ask users if repository exists when a 404 / NotFound is returned
Fixes #67
=> No policy when NuGet warnings are returned

src/GprTool/IoExtensions.cs, src/GprTool/Program.cs, test/GprTool.Tests/IoExtensionsTests.cs
Let the `gpr push` command accept multiple files/glob patterns.
Not a fix for https://github.com/jcansdale/gpr/issues/70. That can be a separate PR.
Fixes #71
=> Add support for pushing multiple globs/files

src/GprTool/GraphQLUtilities.cs, src/GprTool/Program.cs
This PR fixes pagination for the `files`, `delete`, and `list` commands. There _shouldn't_ be any more limits on the number of packages, package versions or files!
Fixes #75
=> List or delete all packages

src/GprTool/IoExtensions.cs, src/GprTool/Program.cs, test/GprTool.Tests/IoExtensionsTests.cs
Now that multiple globs can be passed in as args, we don't need to support separating globs with whitespace.
- Add test for glob with space
https://github.com/jcansdale/gpr/blob/9352233faf97c6a961df726a1624c4c09ceeac3e/test/GprTool.Tests/IoExtensionsTests.cs#L16
- Remove support for separating globs with whitespace
- Don't special case `.` (treat it as a regular directory)
- Add null check for glob patterns (a package path or glob must be passed)
Fixes #70
=> Don't split spaces

src/GprTool/GraphQLUtilities.cs, src/GprTool/Program.cs
There is a bug in `Octokit.GraphQL` that limits outer queries to 200 elements (see https://github.com/octokit/octokit.graphql.net/issues/227). This means that if there are over 200 packages (or deleted packages), the newest packages won't be visible. This PR does manual paging to ensure that all packages are visible.
- Make `gpr list` page through all packages
- Make `gpr files` page through all packages
- Make `gpr delete` page through all packages
- Remove support for implicitly listing viewer packages
Fixes #81
=> Page though all packages

src/GprTool/Program.cs
Add a simple filter to allow a specific version names to be deleted. This is a pale imitation of what we would like to do in #77!
I've manually tested it and it seems to work:
```
gpr delete jcansdale-test/maven-test/com.mycompany.app.my-app -k $GITHUB_TOKEN --version 0.111-SNAPSHOT --force
com.mycompany.app.my-app
Deleting '0.111-SNAPSHOT'
Public package versions are not eligible for deletion. For more on our deletion policy, see https://docs.github.com/articles/about-github-package-registry/#deleting-a-package.
```
This is expected for public packages. ☝️ 
Fixes #86
=> Add option to delete specific version

.github/workflows/action.yml, .github/workflows/docker.yml, .github/workflows/dotnetcore.yml, src/GprTool/Program.cs
When obfuscating a PAT, only encode the first char to avoid verbose strings.
=> Only encode first char

src/GprTool/GprTool.csproj
This is to fix issues like this on .NET 5.0:
```
It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '3.0.0' was not found.
- The following frameworks were found:
5.0.0-preview.8.20407.11 at [C:\hostedtoolcache\windows\dncs\5.0.100-preview.8.20417.9\x64\shared\Microsoft.NETCore.App]
You can resolve the problem by installing the specified framework and/or SDK.
The specified framework can be found at:
- https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=3.0.0&arch=x64&rid=win10-x64
```
=> Set RollForward=LatestMajor so the tool will run with newer runtimes.

.github/workflows/docker.yml
Use default GitHub Actions workflow token when pushing to ghcr.io.
=> Use ${{ github.token }} for ghcr.io

README.md, src/GprTool/NuGetUtilities.cs, src/GprTool/Program.cs, test/GprTool.Tests/NuGetUtilitiesTests.cs
This PR makes it possible to use a private instance's repo URL when pushing packages.
=> Support using private instance repo URL in upload

src/GprTool/NuGetUtilities.cs, src/GprTool/Program.cs, test/GprTool.Tests/NuGetUtilitiesTests.cs
For example.
```
gpr push foo.nuget --subdomain-isolation=true
```
Fixes #119
=> Support pusing NuGet packages to GHES with subdomain isolation
